language: elixir
sudo: false
cache:
  directories:
    - priv/plts
elixir:
  - 1.8
  - 1.7
otp_release:
  - 20.3
  - 18.2.1
before_script:
  - mix deps.get
script: make test/all
env:
  - MIX_ENV=test
notifications:
  recipients:
    - travis@coryodaniel.com
jobs:
  include:
    - stage: dialyzer
      script: mix dialyzer
    - stage: coverage
      script: mix coveralls.travis
